version: "3.7"
services:
   fusta:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - cryogenicplanet/fusta:1.0
    ports:
      - "8888:8888"
    init: true
    stdin_open: true
    tty: true